spec:
  containers:
    - name: clarity-backend
      image: /CLARITY_DB/RETAIL/CLARITY_REPOSITORY_DEV/clarity-backend:latest
      env:
        ENVIRONMENT: production
        SNOWFLAKE_ACCOUNT: WB19670-C2GPARTNERS
        SNOWFLAKE_USER: CLARITY_SERVICE_USER_DEV
        SNOWFLAKE_DATABASE: CLARITY_DB
        SNOWFLAKE_SCHEMA: RETAIL
        SNOWFLAKE_WAREHOUSE: POWERHOUSE
        SNOWFLAKE_ROLE: CLARITY_SERVICE_ROLE_DEV
      resources:
        requests:
          cpu: 0.5
          memory: 1Gi
        limits:
          cpu: 2
          memory: 4Gi

    - name: clarity-frontend
      image: /CLARITY_DB/RETAIL/CLARITY_REPOSITORY_DEV/clarity-frontend:latest
      resources:
        requests:
          cpu: 0.25
          memory: 256Mi
        limits:
          cpu: 1
          memory: 1Gi

    - name: clarity-proxy
      image: /CLARITY_DB/RETAIL/CLARITY_REPOSITORY_DEV/clarity-proxy:latest
      env:
        FRONTEND_SERVICE: localhost:8080
        BACKEND_SERVICE: localhost:8082
      resources:
        requests:
          cpu: 0.25
          memory: 256Mi
        limits:
          cpu: 0.5
          memory: 512Mi

  endpoints:
    - name: clarity
      port: 8000
      public: true

  platformMonitor:
    metricConfig:
      groups:
        - system
